Hw05 avatars
Mariia1986/contacts-rest-api pull request #4
Opened 2021-06-14 10:01 UTC by Mariia1986

Проверьте, пожалуйста!

2021-06-14 20:24 UTC, Danil44 requested changes

2021-06-14 20:24 UTC, Danil44 commented on bin/server.js
> +const createFolderIsNotExist = require('../helpers/create-folder')
Незрозуміла назва змінної, що вона означає?

2021-06-14 20:24 UTC, Danil44 commented on controlers/users.js
> +const avatars = async (req, res, next) => {
Назва більше підходить для масиву, а не для функції яка виконує якусь дію

2021-06-14 20:24 UTC, Danil44 commented on controlers/users.js
> +    const id = req.user.id
Те саме, це назва для масиву, а не об‘єкту

2021-06-16 09:52 UTC, Mariia1986 commented on bin/server.js
> +const createFolderIsNotExist = require('../helpers/create-folder')
создать папку, если таковой не существует)

2021-06-16 20:49 UTC, merged